package view;

import control.PersistenciaPessoa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pessoa;

public class TelaLogin extends javax.swing.JFrame {

    public TelaLogin() {
        initComponents();
        buttonGroup.add(jRadioButtonAluno);
        buttonGroup.add(jRadioButtonCoordenador);
        buttonGroup.add(jRadioButtonProfessor);
        buttonGroup.add(jRadioButtonRH);
        buttonGroup.add(jRadioButtonSecretaria);
        jRadioButtonSecretaria.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jRadioButtonSecretaria = new javax.swing.JRadioButton();
        jRadioButtonRH = new javax.swing.JRadioButton();
        jRadioButtonProfessor = new javax.swing.JRadioButton();
        jRadioButtonCoordenador = new javax.swing.JRadioButton();
        jRadioButtonAluno = new javax.swing.JRadioButton();
        jFormattedTextFieldMatricula = new javax.swing.JFormattedTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelMatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelMatricula.setText("Matrícula:");

        jLabelSenha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelSenha.setText("Senha:");

        jButtonLogin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jRadioButtonSecretaria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButtonSecretaria.setText("Secretaria");

        jRadioButtonRH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButtonRH.setText("RH");

        jRadioButtonProfessor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButtonProfessor.setText("Professor");

        jRadioButtonCoordenador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButtonCoordenador.setText("Coordenador");

        jRadioButtonAluno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jRadioButtonAluno.setText("Aluno");

        try {
            jFormattedTextFieldMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPasswordFieldSenha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonAluno)
                    .addComponent(jRadioButtonCoordenador)
                    .addComponent(jRadioButtonProfessor)
                    .addComponent(jRadioButtonRH)
                    .addComponent(jRadioButtonSecretaria)
                    .addComponent(jLabelSenha)
                    .addComponent(jLabelMatricula)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldMatricula)
                    .addComponent(jPasswordFieldSenha))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jRadioButtonSecretaria)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonRH)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonProfessor)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonCoordenador)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonAluno)
                .addGap(42, 42, 42)
                .addComponent(jLabelMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String matricula = jFormattedTextFieldMatricula.getText();
        String senha = senhaToString(jPasswordFieldSenha.getPassword());
        String funcao = getFuncao();
        Pessoa pessoaLogin = new Pessoa();
        pessoaLogin.setPes_iden(matricula);
        pessoaLogin.setPes_funcao(funcao);
        String sqlQuery = "SELECT * FROM pessoa WHERE pes_funcao = '" + pessoaLogin.getPes_funcao() + "' " + "AND pes_iden = '" + pessoaLogin.getPes_iden() + "'";
        ArrayList<Pessoa> lista_pessoa = PersistenciaPessoa.ListaPessoas(sqlQuery);
        
        if(lista_pessoa.isEmpty() || !lista_pessoa.get(0).getPes_iden().replaceAll("-", "").equals(senha)) {
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado");
        }
        else {
            try {
                TelaPrincipal tp = new TelaPrincipal(lista_pessoa.get(0));
                tp.setVisible(rootPaneCheckingEnabled);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private String senhaToString(char[] senha) {
        String s =  "";
        for(char c : senha) {
            s += c;
        }
        return s;
    }
    
    private String getFuncao() {
        if(jRadioButtonAluno.isSelected()) {
            return "Aluno";
        }
        if(jRadioButtonCoordenador.isSelected()) {
            return "Coordenador";
        }
        if(jRadioButtonProfessor.isSelected()) {
            return "Professor";
        }
        if(jRadioButtonRH.isSelected()) {
            return "RH";
        }
        if(jRadioButtonSecretaria.isSelected()) {
            return "Secretaria";
        }
        return null;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JFormattedTextField jFormattedTextFieldMatricula;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JRadioButton jRadioButtonAluno;
    private javax.swing.JRadioButton jRadioButtonCoordenador;
    private javax.swing.JRadioButton jRadioButtonProfessor;
    private javax.swing.JRadioButton jRadioButtonRH;
    private javax.swing.JRadioButton jRadioButtonSecretaria;
    // End of variables declaration//GEN-END:variables
}
